version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.0
    working_directory: ~/hugo
    steps:
      - checkout
      - run:
         name: install
         command: |
            go get -v github.com/spf13/hugo
            git config --global user.email "takahashi1364@gmail.com"
            git config --global user.name "tshohe"

      - run:
          name: build and deploy
          command: | 
            hugo
            git clone https://github.com/tshohe/tshohe.github.io.git
            cp -af public/* tshohe.github.io/
            cd tshohe.github.io
            pwd
            find . | sort | sed '1d;s/^\.//;s/\/\([^/]*\)$/|--\1/;s/\/[^/|]*/|  /g'
            git add .
            git commit -m "[ci skip] publish"
            git push origin master
