defaults: &defaults
  docker:
      - image: circleci/golang:1.12.0

version: 2
jobs:
  build:
    <<: *defaults
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run:
          command: |
             go get -v github.com/spf13/hugo
             git config --global user.email "takahashi1364@gmail.com"
             git config --global user.name "tshohe"

  deploy:
    <<: *defaults
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - restore_cache:
          key: hugo-cache
      - run:
           command: | 
             git clone https://github.com/tshohe/tshohe.github.io.git
             cp -rp public/* tshohe.github.io/
             cd tshohe.github.io
             git diff
             git add .
             git commit -m "publish"
             git push origin master

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - build
