defaults: &defaults
  docker:
      - image: jojomi/hugo:latest

version: 2
jobs:
  build:
    <<: *defaults
    working_directory: ~/hugo
    steps:
      - checkout
      - run: 
           command: ls
      - run:
          command: hugo
      - save_cache:
          key: hugo-cache
          paths:
            - ~/hugo

  deploy:
    <<: *defaults
    working_directory: ~/hugo/public
    steps:
      - restore_cache:
          key: hugo-cache
      - run:
           command: ls
      - run:
           command: git add .
      - run:
           command: git commit -m "publish"
      - run:
           command: git push origin master

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - build
