defaults: &defaults
  docker:
      - image: jojomi/hugo:latest

version: 2
jobs:
  build:
    <<: *defaults
    working_directory: ~/hugo
    steps:
      - checkout
      - run:
          command: |
            rm -rf public/*
            hugo
      - save_cache:
          key: hugo-cache
          paths:
            - ~/hugo

  deploy:
    <<: *defaults
    working_directory: ~/hugo
    steps:
      - restore_cache:
          key: hugo-cache
      - run:
           command: | 
             git clone https://github.com/tshohe/tshohe.github.io.git
             cp -rp public/* tshohe.github.io/
             cd tshohe.github.io
             git remote set-url origin git@github.com:tshohe/tshohe.github.io.git
             git config --global user.email "takahashi1364@gmail.com"
             git config --global user.name "tshohe"
             git add .
             git commit -m "publish"
             git push origin master

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - build
