defaults: &defaults
  docker:
      - image: jojomi/hugo:latest

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          command: date
      - run:
          command: hugo

  deploy:
    <<: *defaults
    working_directory: ~/public
    steps:
      - run:
           command: git add .
      - run:
           command: git commit -m "publish"
      - run:
           command: git push origin master

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - build
